### ISSUE TITLE
Separate CI build and simulation run

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm-examples#66]
Separate CI build and simulation run, so the building queue is no blocked by the simulation getting stuck that runs right after the build. Once we have split build and simulation, we could also run simulation in parallel then.

**Comment by jingjin666** [comment]
[Failed build]

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jingjin/workspace/sel4-hypervisor/projects/camkes-tool/camkes/runner/__main__.py", line 316, in <module>
    sys.exit(main(sys.argv, sys.stdout, sys.stderr))
  File "/home/jingjin/workspace/sel4-hypervisor/projects/camkes-tool/camkes/runner/__main__.py", line 292, in main
    g = r.render(i, assembly, template, render_state, obj_key,
  File "/home/jingjin/workspace/sel4-hypervisor/projects/camkes-tool/camkes/runner/Renderer.py", line 89, in render
    t = self.env.get_template(template)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 405, in load
    return loader.load(environment, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jingjin/workspace/sel4-hypervisor/projects/vm/templates/seL4VMParameters.template.c", line 23, in <module>
    /*- set entry_offset = 0x80000 if is_64_bit else 0x8000 -*/
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/lib/python3/dist-packages/jinja2/parser.py", line 888, in subparse
    self.stream.expect('block_end')
  File "/usr/lib/python3/dist-packages/jinja2/lexer.py", line 386, in expect
    raise TemplateSyntaxError("expected token %r, got %r" %
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'x80000'
[299/388] Building C object kernel/CMakeFiles/kernel.elf.dir/kernel_all.c.obj

![image](https://github.com/seL4/camkes-vm-examples/assets/37563327/d8360baa-a43d-4c02-ac6a-4f0db660edd4)

repo init -u https://github.com/seL4/camkes-vm-examples-manifest.git
repo sync
mkdir build
cd build
../init-build.sh -DCAMKES_VM_APP=vm_minimal -DPLATFORM=qemu-arm-virt -DAARCH64=TRUE
ninja
